# Generated by Django 5.2.11 on 2026-03-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
