# Generated by Django 5.2.11 on 2026-03-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_selected',
            new_name='is_active',
        ),
    ]
