# Generated by Django 6.0.1 on 2026-01-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='text',
            new_name='original_text',
        ),
        migrations.RenameField(
            model_name='sentencerevision',
            old_name='text',
            new_name='original_text',
        ),
    ]
