# Generated by Django 6.0.1 on 2026-01-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_rename_text_sentence_original_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencerevision',
            name='translated_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sentencerevision',
            name='original_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sentencerevision',
            name='revision',
            field=models.JSONField(default=dict),
        ),
    ]
