services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: polyglossia
      POSTGRES_PASSWORD: polyglossia
      POSTGRES_DB: polyglossia
    ports:
      - "127.0.0.1:5632:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
