# Generated by Django 5.2.11 on 2026-03-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('context', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generating_flashcards_status', models.CharField(choices=[('NULL', 'NULL'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED'), ('DONE', 'DONE')], default='NULL', max_length=20)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='profiles.profile')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='vocabulary.word')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('exported_at'), descending=True, nulls_first=True), models.OrderBy(models.F('created_at'), descending=True)],
            },
        ),
    ]
