# Generated by Django 5.2.11 on 2026-03-06 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('context', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generating_flashcards_status', models.CharField(choices=[('NULL', 'NULL'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED'), ('DONE', 'DONE')], default='NULL', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='vocabulary.word')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('exported_at'), descending=True, nulls_first=True), models.OrderBy(models.F('created_at'), descending=True)],
            },
        ),
    ]
