# Generated by Django 5.2.11 on 2026-03-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='word',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='profiles.profile'),
        ),
    ]
