# Generated by Django 6.0.1 on 2026-01-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_flashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='context',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
