# Generated by Django 6.0.1 on 2026-01-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_word_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
