# Generated by Django 6.0.1 on 2026-01-24 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0004_flashcard_is_selected"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashcard",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="flashcard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
