# Generated by Django 6.0.1 on 2026-01-24 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0005_alter_flashcard_options_flashcard_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flashcard",
            old_name="is_selected",
            new_name="is_active",
        ),
    ]
