# Generated by Django 6.0.1 on 2026-01-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0007_flashcard_last_exported_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='last_exported_at',
            new_name='exported_at',
        ),
    ]
