# Generated by Django 6.0.1 on 2026-01-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_rename_last_exported_at_flashcard_exported_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': [models.OrderBy(models.F('exported_at'), descending=True, nulls_first=True)]},
        ),
    ]
