# Generated by Django 6.0.1 on 2026-01-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0009_alter_flashcard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': [models.OrderBy(models.F('exported_at'), descending=True, nulls_first=True), models.OrderBy(models.F('created_at'), descending=True)]},
        ),
    ]
