# Generated by Django 6.0.1 on 2026-01-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0010_alter_flashcard_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='vocabulary.word'),
        ),
    ]
