# Generated by Django 6.0.1 on 2026-01-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0012_word_generating_anki_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='generating_anki_status',
            new_name='generating_flashcards_status',
        ),
    ]
