name: Deploy Prod

on:
  push:
    branches: [ tenant-mode ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            #!/bin/bash

            set -ex

            if [ ! -d "polyglossia" ]; then
              git clone https://github.com/franciszek-szeptycki/polyglossia.git
            fi

            cd polyglossia

            git checkout -b tenant-mode || true

            git pull origin tenant-mode

            docker compose down || true
            docker compose up -d --build

            timeout 30s docker compose logs -f

            if docker compose ps | grep -q 'healthy'; then
              exit 0
            else
              exit 1
            fi
